# Generated by Django 4.1.2 on 2022-10-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('text', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('published', models.DateField()),
                ('cover', models.ImageField(upload_to='covers')),
                ('summary', models.TextField()),
                ('publisher', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('tags', models.ManyToManyField(to='api.tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
